function createDriveImageElement(image){const img=document.createElement('img');img.alt=image.name||'question image';img.loading="lazy";img.decoding="async";const fileId=image.fileId;const ceId=image.CEfileID;function buildUrls(id){return[`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w2000`,`https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w1000`,`https://drive.google.com/uc?export=view&id=${encodeURIComponent(id)}`];}const eeUrls=fileId?buildUrls(fileId):[];const ceUrls=ceId?buildUrls(ceId):[];let currentIndex=0;let currentMode="CE";let urlIndex=0;function loadImage(urlList){if(!urlList.length){img.src=createPlaceholderImage(image.name||'No image',600,400);return;}urlIndex=0;img.src=urlList[urlIndex];img.onerror=function(){urlIndex++;if(urlIndex<urlList.length){img.src=urlList[urlIndex];}else{img.onerror=null;img.src=createPlaceholderImage(image.name||'Load fail',600,400);}};}loadImage(ceUrls.length?ceUrls:eeUrls);if(fileId){img.style.cursor="pointer";img.title="Click to toggle EE ↔ CE";img.addEventListener("click",function(){if(currentMode==="CE"){currentMode="EE";loadImage(eeUrls);}else{currentMode="CE";loadImage(ceUrls);}});}return img;}function openDrivePopup(fileId,titleText='Preview',type='pdf'){if(!fileId||!String(fileId).trim()){alert('沒有可開啟的 Google Drive ID。');return;}const cleanId=String(fileId).trim();const url=type==='image'?`https://drive.google.com/thumbnail?id=${encodeURIComponent(cleanId)}&sz=w2000`:`https://drive.google.com/file/d/${encodeURIComponent(cleanId)}/preview`;const popup=window.open('','_blank','width=1000,height=800');if(!popup){alert('瀏覽器封鎖了彈出視窗，請先允許彈出視窗。');return;}const body=type==='image'?`<div class="image-wrap"><img src="${url}" alt="${escapeHtml(titleText)}"></div>`:`<iframe src="${url}"></iframe>`;popup.document.write(`<!DOCTYPE html><html lang="zh-Hant"><head><meta charset="UTF-8"><title>${escapeHtml(titleText)}</title><style>
        html,body{margin:0;padding:0;width:100%;height:100%;overflow:hidden;background:#f4f4f4;font-family:Arial,sans-serif;}
        .pdf-header{height:44px;line-height:44px;padding:0 12px;background:#4a6fa5;color:white;font-size:14px;}
        iframe{width:100%;height:calc(100% - 44px);border:none;background:white;}
        .image-wrap{height:calc(100% - 44px);overflow:auto;text-align:center;padding:12px;}
        .image-wrap img{max-width:100%;height:auto;background:white;border:1px solid #ddd;}
      </style></head><body><div class="pdf-header">${escapeHtml(titleText)}</div>${body}</body></html>`);popup.document.close();}function escapeHtml(s){return String(s).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }

    function createPlaceholderImage(filename, width=300, height=200) {
      const safe = escapeHtml(filename);
      const svg = `<svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg"><rect width="100%" height="100%" fill="#4a6fa5"/><text x="50%" y="50%" text-anchor="middle" dy="0.3em" fill="white" font-family="Arial" font-size="14">${safe}</text></svg>`;
      return `data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(svg)))}`;
    }

    